### ISSUE TITLE
Ownership of ros-interactive-manipulation

### ISSUE THREAD

**Issue by davetcoleman** [ros-interactive-manipulation/tabletop_object_perception#3]
I'm working on releasing MoveIt! into ROS-K, see https://github.com/ros-planning/moveit_ros/issues/695, and two packages are blocking its release from this org. @isucan just made me a member of `ros-interactive-manipulation` - thank you. I can now see the _14_ members of this Github organization. It appears most of the members have moved on to other companies and are no longer active on this ROS project.

Per [ROS policy](http://wiki.ros.org/RecommendedRepositoryUsage/CommonGitHubOrganizations#Guidelines_for_administering_ros-.2A_organizations_on_GitHub) the ROS platform manager is an owner on all `ros-*` repos to support maintainer handoffs. @tfoote

The 3 current owners of this project are @ablasdel @adamantivm @aleeper - can one of you add @tfoote to be an owner of this org?

@130s is currently leading the release of MoveIt! debians - I think he should also be a member of this org and associated release repos so he can release these two packages:
https://github.com/ros-interactive-manipulation/manipulation_msgs/issues/7
https://github.com/ros-interactive-manipulation/household_objects_database_msgs/issues/3

**Comment by davetcoleman** [comment]
correction: there are more than 3 owners

**Comment by isucan** [comment]
Just added @tfoote as an owner.

**Comment by tfoote** [comment]
Thanks @isucan @130s I've invited you to a @ros-interactive-manipulation/maintainers  team which has access to those repos.
